name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install

      - name: Authenticate to Salesforce
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
          SF_LOGIN_URL: https://test.salesforce.com  # Use https://login.salesforce.com for production
        run: |
          echo "Authenticating to Salesforce..."
          echo "$SF_PRIVATE_KEY" > private_key.pem
          sfdx force:auth:jwt:grant --clientid $SF_CLIENT_ID --username $SF_USERNAME --jwtkeyfile private_key.pem --setdefaultdevhubusername --setalias myDevHub

      - name: Deploy Metadata
        run: |
          echo "Deploying metadata to Salesforce..."
          sfdx force:source:deploy -p path/to/your/metadata --testlevel RunLocalTests
