name: Deploy Metadata

on:
  push:
    branches:
      - main

jobs:
  call-common-steps:
    uses: ./.github/workflows/generic-steps.yml

  additional-steps:
    runs-on: ubuntu-latest
    needs: call-common-steps  # Ensure this job runs after the common steps

    steps:
      - name: Deploy Metadata
        run: |
            echo "Deploying metadata to INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests
