name: Deploy/Deploy Metadata

on:
  pull_request:
    types: [opened, reopened, synchronize]  # Triggers on PR creation and updates
  push:
    branches:
      - main  # Triggers on merge to main branch

jobs:
  conditional-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
            echo "Installing Salesforce CLI..."
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                  mkdir ~/sfdx
                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                  ~/sfdx/bin/sfdx version

      - name: 'Populate SF_AUTH_URL'
        shell: bash
        run: |
            echo ${{ secrets.SF_AUTH_URL}} > ./SF_AUTH_URL.txt

      - name: 'Authenticate MBAM_INT Sandbox'
        run: |
            echo "Authenticating to MBAM_INT Sandbox..."
            sf org login sfdx-url --alias=MBAM_INT --sfdx-url-file=./SF_AUTH_URL.txt --set-default

      - name: Run on PR Create
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'  # This step runs only on PR creation
        run: |
            echo "Validating metadata against INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests --dry-run

      - name: Run on PR Merge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # This step runs only on PR merge to main
        run: |
            echo "Deploying metadata to INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests
