name: Deploy/Deploy Metadata

on:
  pull_request:
    types: [opened, reopened, synchronize]  # Triggers on PR creation and updates
  push:
    branches:
      - main  # Triggers on merge to main branch

permissions:
  contents: read
  pull-requests: write

jobs:
  conditional-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
            npm install @salesforce/cli --global

      # Temporarily disabled sfdx git until the plugin is updated to use sf commands instead of sfdx
      # - name: 'Install sfdx git delta'
      #   run: |
      #       echo y | sf plugins:install sfdx-git-delta
      #       sf plugins

      # - name: 'Populate delta changes'
      #   run: |
      #       java --version
      #       mkdir changed-sources
      #       sfdx sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta

      - name: 'Install Salesforce Code Analyzer'
        run: sf plugins install @salesforce/sfdx-scanner

      - name: 'Analyze code'
        run: |
            sf scanner run --format sarif --outfile CodeAnalyzerResults.sarif --target './**/*.cls' --category 'Design,Best Practices,Performance'

      - name: Upload CodeAnalyzer results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: CodeAnalyzerResults.sarif

      - name: 'Populate Salesforce AUTH URL'
        shell: bash
        run: |
            echo ${{ secrets.SF_AUTH_URL}} > ./SF_AUTH_URL.txt

      - name: 'Authenticate MBAM_INT Sandbox'
        run: |
            echo "Authenticating to MBAM_INT Sandbox..."
            sf org login sfdx-url --alias=MBAM_INT --sfdx-url-file=./SF_AUTH_URL.txt --set-default

      - name: Run on PR Create/Update
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'  # This step runs only on PR creation
        run: |
            echo "Validating metadata against INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests --dry-run

      - name: Run on PR Merge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # This step runs only on PR merge to main
        run: |
            echo "Deploying metadata to INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests
