name: Validate Metadata

on:
    pull_request:
      types: [opened, synchronize]
      branches: [ main ]

jobs:
  call-common-steps:
    uses: ./.github/workflows/generic-steps.yml

  additional-steps:
    runs-on: ubuntu-latest
    needs: call-common-steps  # Ensure this job runs after the common steps

    steps:
      - name: Validate Metadata
        run: |
            echo "Validating metadata against INT sandbox..."
            sf project deploy start --source-dir=force-app/main --test-level=RunLocalTests --dry-run
